FROM rabbitmq:alpine
# https://github.com/docker-library/rabbitmq/blob/79277042564875d55e4b05a60c65b6eb46651a94/3.6/alpine/management/Dockerfile

RUN rabbitmq-plugins enable --offline rabbitmq_management

EXPOSE 15671 15672
